server.port=8888
spring.application.name=config-service

spring.cloud.config.server.git.uri=https://github.com/hartiIga/learning_microservices-config-repo
spring.cloud.config.server.git.default-label=main

spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-service

spring.cloud.config.enabled=true

spring.cloud.config.fail-fast=true

spring.cloud.config.retry.enabled=true
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.max-interval=10000
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.multiplier=2
