spring.application.name=gateway-service
server.port=8181

#eureka
application.config.registry-url=http://registry-service:8761/eureka
eureka.client.service-url.defaultZone=http://registry-service:8761/eureka

#gateway

#Auto-creates routes based on Eureka service name
spring.cloud.gateway.discovery.locator.enabled=true 
#Allows calling /student-service/ instead of /STUDENT-SERVICE/
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
